// Dummy Data
const dbUsers = [
  {
    id: 1,
    name: 'Lindsay Walton',
    slug: 'lindsay-walton',
    email: 'lindsay.walton@example.com',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=1',
  },
  {
    id: 2,
    name: 'Courtney Henry',
    slug: 'courtney-henry',
    email: 'courtney.henry@example.com',
    role: 'Editor',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=2',
  },
  {
    id: 3,
    name: 'Tom Cook',
    slug: 'tom-cook',
    email: 'tom.cook@example.com',
    role: 'Viewer',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=3',
  },
  {
    id: 4,
    name: 'Whitney Francis',
    slug: 'whitney-francis',
    email: 'whitney.francis@example.com',
    role: 'Editor',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=4',
  },
  {
    id: 5,
    name: 'Leonard Krasner',
    slug: 'leonard-krasner',
    email: 'leonard.krasner@example.com',
    role: 'Admin',
    status: 'Inactive',
    avatar: 'https://i.pravatar.cc/150?u=5',
  },
  {
    id: 6,
    name: 'Floyd Miles',
    slug: 'floyd-miles',
    email: 'floyd.miles@example.com',
    role: 'Viewer',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=6',
  },
  {
    id: 7,
    name: 'Emily Selman',
    slug: 'emily-selman',
    email: 'emily.selman@example.com',
    role: 'Editor',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=7',
  },
  {
    id: 8,
    name: 'Kristin Watson',
    slug: 'kristin-watson',
    email: 'kristin.watson@example.com',
    role: 'Viewer',
    status: 'Inactive',
    avatar: 'https://i.pravatar.cc/150?u=8',
  },
  {
    id: 9,
    name: 'Cody Fisher',
    slug: 'cody-fisher',
    email: 'cody.fisher@example.com',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=9',
  },
  {
    id: 10,
    name: 'Esther Howard',
    slug: 'esther-howard',
    email: 'esther.howard@example.com',
    role: 'Editor',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=10',
  },
  {
    id: 11,
    name: 'Jenny Wilson',
    slug: 'jenny-wilson',
    email: 'jenny.wilson@example.com',
    role: 'Viewer',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=11',
  },
  {
    id: 12,
    name: 'Guy Hawkins',
    slug: 'guy-hawkins',
    email: 'guy.hawkins@example.com',
    role: 'Editor',
    status: 'Inactive',
    avatar: 'https://i.pravatar.cc/150?u=12',
  },
  {
    id: 13,
    name: 'Robert Fox',
    slug: 'robert-fox',
    email: 'robert.fox@example.com',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=13',
  },
  {
    id: 14,
    name: 'Jacob Jones',
    slug: 'jacob-jones',
    email: 'jacob.jones@example.com',
    role: 'Viewer',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=14',
  },
  {
    id: 15,
    name: 'Darlene Robertson',
    slug: 'darlene-robertson',
    email: 'darlene.robertson@example.com',
    role: 'Editor',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=15',
  },
  {
    id: 16,
    name: 'Theresa Webb',
    slug: 'theresa-webb',
    email: 'theresa.webb@example.com',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=16',
  },
  {
    id: 17,
    name: 'Kathryn Murphy',
    slug: 'kathryn-murphy',
    email: 'kathryn.murphy@example.com',
    role: 'Viewer',
    status: 'Inactive',
    avatar: 'https://i.pravatar.cc/150?u=17',
  },
  {
    id: 18,
    name: 'Gregory Lane',
    slug: 'gregory-lane',
    email: 'gregory.lane@example.com',
    role: 'Editor',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=18',
  },
  {
    id: 19,
    name: 'Savannah Nguyen',
    slug: 'savannah-nguyen',
    email: 'savannah.nguyen@example.com',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=19',
  },
  {
    id: 20,
    name: 'Marvin McKinney',
    slug: 'marvin-mckinney',
    email: 'marvin.mckinney@example.com',
    role: 'Viewer',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=20',
  },
  {
    id: 21,
    name: 'Bessie Cooper',
    slug: 'bessie-cooper',
    email: 'bessie.cooper@example.com',
    role: 'Editor',
    status: 'Inactive',
    avatar: 'https://i.pravatar.cc/150?u=21',
  },
  {
    id: 22,
    name: 'Cameron Williamson',
    slug: 'cameron-williamson',
    email: 'cameron.williamson@example.com',
    role: 'Viewer',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=22',
  },
  {
    id: 23,
    name: 'Brooklyn Simmons',
    slug: 'brooklyn-simmons',
    email: 'brooklyn.simmons@example.com',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=23',
  },
  {
    id: 24,
    name: 'Leslie Alexander',
    slug: 'leslie-alexander',
    email: 'leslie.alexander@example.com',
    role: 'Editor',
    status: 'Active',
    avatar: 'https://i.pravatar.cc/150?u=24',
  },
  {
    id: 25,
    name: 'Eleanor Pena',
    slug: 'eleanor-pena',
    email: 'eleanor.pena@example.com',
    role: 'Viewer',
    status: 'Inactive',
    avatar: 'https://i.pravatar.cc/150?u=25',
  },
];

export default defineEventHandler((event) => {
  // get slug from url (/api/users/testing-user)
  const slug = getRouterParam(event, 'slug');

  const user = dbUsers.find((u) => u.slug === slug);

  if (!user) {
    throw createError({
      statusCode: 404,
      statusMessage: 'User not found',
    });
  }

  return user;
});
